import type { LandmarkRule } from '@/lib/poseAnalyzer';

/** Backend `landmark_rules` boş geldiğinde test pozları için yerel kurallar (geliştirme / fallback). */
export const FALLBACK_RULES_BY_POSE_ID: Record<string, LandmarkRule[]> = {
  test_right_arm_up: [
    {
      rule_id: 'right_shoulder',
      point_a: 24,
      point_b: 12,
      point_c: 14,
      angle_min: 150,
      angle_max: 180,
      weight: 0.5,
      rule_type: 'target',
      feedback_tr: 'Sağ kolunuzu daha yukarı kaldırın.',
      feedback_en: 'Raise your right arm higher.',
    },
    {
      rule_id: 'right_elbow',
      point_a: 12,
      point_b: 14,
      point_c: 16,
      angle_min: 160,
      angle_max: 180,
      weight: 0.5,
      rule_type: 'target',
      feedback_tr: 'Sağ dirseğinizi bükmeyin, dümdüz tutun.',
      feedback_en: 'Keep your right elbow straight.',
    },
    {
      rule_id: 'torso_lean',
      point_a: 12,
      point_b: 24,
      point_c: 26,
      angle_min: 0,
      angle_max: 160,
      weight: 0.15,
      rule_type: 'fault',
      fault_penalty_percent: 15,
      feedback_tr: 'Gövdenizi yana eğmeyin, dik durun.',
      feedback_en: "Don't lean your torso, stand straight.",
    },
  ],
  test_bend_elbows: [
    {
      rule_id: 'left_elbow',
      point_a: 11,
      point_b: 13,
      point_c: 15,
      angle_min: 10,
      angle_max: 60,
      weight: 0.5,
      rule_type: 'target',
      feedback_tr: 'Sol dirseğinizi daha fazla bükün.',
      feedback_en: 'Bend your left elbow more.',
    },
    {
      rule_id: 'right_elbow',
      point_a: 12,
      point_b: 14,
      point_c: 16,
      angle_min: 10,
      angle_max: 60,
      weight: 0.5,
      rule_type: 'target',
      feedback_tr: 'Sağ dirseğinizi daha fazla bükün.',
      feedback_en: 'Bend your right elbow more.',
    },
  ],
  test_t_pose: [
    {
      rule_id: 'left_shoulder_raise',
      point_a: 23,
      point_b: 11,
      point_c: 13,
      angle_min: 75,
      angle_max: 105,
      weight: 0.25,
      rule_type: 'target',
      feedback_tr: 'Sol kolunuzu yere paralel hizaya getirin.',
      feedback_en: 'Keep left arm parallel to floor.',
    },
    {
      rule_id: 'right_shoulder_raise',
      point_a: 24,
      point_b: 12,
      point_c: 14,
      angle_min: 75,
      angle_max: 105,
      weight: 0.25,
      rule_type: 'target',
      feedback_tr: 'Sağ kolunuzu yere paralel hizaya getirin.',
      feedback_en: 'Keep right arm parallel to floor.',
    },
    {
      rule_id: 'left_elbow_straight',
      point_a: 11,
      point_b: 13,
      point_c: 15,
      angle_min: 160,
      angle_max: 180,
      weight: 0.25,
      rule_type: 'target',
      feedback_tr: 'Sol kolunuzu tamamen düzeltin.',
      feedback_en: 'Straighten left arm.',
    },
    {
      rule_id: 'right_elbow_straight',
      point_a: 12,
      point_b: 14,
      point_c: 16,
      angle_min: 160,
      angle_max: 180,
      weight: 0.25,
      rule_type: 'target',
      feedback_tr: 'Sağ kolunuzu tamamen düzeltin.',
      feedback_en: 'Straighten right arm.',
    },
  ],
};

export function getFallbackRulesForPose(poseId: string | null): LandmarkRule[] {
  if (!poseId) return [];
  return FALLBACK_RULES_BY_POSE_ID[poseId] ?? [];
}
