export const FLOATING_TAB_BAR_BOTTOM_OFFSET = 20;
export const FLOATING_TAB_BAR_HEIGHT = 62;
export const FLOATING_TAB_BAR_GAP_ABOVE = 12;
export const TAB_SCENE_BOTTOM_PADDING =
  FLOATING_TAB_BAR_BOTTOM_OFFSET + FLOATING_TAB_BAR_HEIGHT + FLOATING_TAB_BAR_GAP_ABOVE;
